// @ts-nocheck
import { ensureDebuggerBridge, normalizeMethodPath } from './page-bridge';

/**
 * gRPC Debugger 1.0 - Frontend Injection Script
 * Redesigned for Connect-RPC and Buf ecosystem support.
 * Now with auto-detection for google-protobuf and protobufjs.
 */

(function () {
  // v2.23: 防止重複注入
  if (window.__GRPC_WEB_INJECTOR_INJECTED__) {
    console.log("[gRPC Debugger] Injector already active, skipping.");
    return;
  }
  window.__GRPC_WEB_INJECTOR_INJECTED__ = true;

  const VERSION = "v2.23";
  const postType = "__GRPCWEB_DEVTOOLS__";
  const bridge = ensureDebuggerBridge(window);
  const bridgeEventSource = '__GRPC_DEBUGGER_BRIDGE_EVENT__';

  function createCallEvent(data) {
    const timestamp = data.timestamp || Date.now();
    return {
      id: data.id || `postmessage-${timestamp}-${Math.random().toString(36).slice(2, 8)}`,
      method: normalizeMethodPath(data.method),
      methodType: data.methodType || 'unary',
      request: data.request || null,
      response: data.error
        ? { _error: data.error.message || String(data.error), _code: data.error.code }
        : data.response || null,
      error: data.error || null,
      url: data.url || '',
      startTime: timestamp,
      status: data.status || 'finished',
      httpStatus: data.httpStatus ?? null,
      grpcStatus: data.grpcStatus ?? (data.error?.code ?? 0),
      grpcMessage: data.grpcMessage ?? (data.error?.message ?? null),
      requestHeaders: data.requestHeaders || {},
      responseHeaders: data.responseHeaders || {},
      _source: 'postmessage',
    };
  }
  console.log(
    `%c[gRPC Debugger ${VERSION}] Injector Active`,
    "color: #8b5cf6; font-weight: bold;",
  );

  // 目前只保留 manual API 入口，註冊 clients 不會自動 hook。
  window.__GRPCWEB_DEVTOOLS__ = window.__GRPCWEB_DEVTOOLS__ || function (clients) {
    return clients;
  };

  /**
   * New 2.0 API: Register a Connect/Buf Service definition
   * @param {Object} service - The service definition generated by @bufbuild/protobuf
   */
  window.__GRPCWEB_DEVTOOLS__.registerService = function (service) {
    if (!service || !service.typeName) {
      console.warn("[gRPC Debugger] Invalid service definition");
      return;
    }

    // Convert Connect/Buf service object to a simplified schema format for the engine
    const services = [
      {
        name: service.typeName.split(".").pop(),
        fullName: service.typeName,
        methods: Object.values(service.methods).map((m) => ({
          name: m.name,
          requestType: m.I.typeName,
          responseType: m.O.typeName,
        })),
      },
    ];

    // We also need the message definitions for these methods
    const messages = {};
    const collectMessages = (msg) => {
      if (!msg || !msg.typeName || messages[msg.typeName]) return;
      messages[msg.typeName] = {
        name: msg.typeName.split(".").pop(),
        fields: msg.fields.map((f) => {
          let fieldType = 9; // 預設 string 而非 0
          if (f.kind === "message" || f.kind === "map") {
            fieldType = 11;
          } else if (f.kind === "scalar") {
            fieldType = f.scalar || 9;
          } else if (f.kind === "enum") {
            fieldType = 14;
          }
          return {
            number: f.no,
            name: f.name,
            type: fieldType,
            type_name: f.T
              ? f.T.typeName
              : f.K
                ? `Map<${f.K.name}, ${f.V.name}>`
                : undefined,
          };
        }),
      };
      msg.fields.forEach((f) => f.T && collectMessages(f.T));
    };

    Object.values(service.methods).forEach((m) => {
      collectMessages(m.I);
      collectMessages(m.O);
    });

    bridge.enqueueSchema({ services, messages }, 'frontend-api:service');

    console.log(`[gRPC Debugger] Registered service: ${service.typeName}`);
  };

  /**
   * New 2.0 API: Register a list of messages
   * @param {Array|Object} msgs - An array or object containing Buf message definitions
   */
  window.__GRPCWEB_DEVTOOLS__.registerMessages = function (msgs) {
    const messages = {};
    const msgList = Array.isArray(msgs) ? msgs : Object.values(msgs);

    const collect = (msg) => {
      if (!msg || !msg.typeName || messages[msg.typeName]) return;
      messages[msg.typeName] = {
        name: msg.typeName.split(".").pop(),
        fields: msg.fields.map((f) => {
          let fieldType = 9; // 預設 string
          if (f.kind === "message" || f.kind === "map") {
            fieldType = 11;
          } else if (f.kind === "scalar") {
            fieldType = f.scalar || 9;
          } else if (f.kind === "enum") {
            fieldType = 14;
          }
          return {
            number: f.no,
            name: f.name,
            type: fieldType,
            type_name: f.T ? f.T.typeName : undefined,
          };
        }),
      };
      msg.fields.forEach((f) => f.T && collect(f.T));
    };

    msgList.forEach(collect);

    bridge.enqueueSchema({ messages }, 'frontend-api:messages');

    console.log("[gRPC Debugger] Registered message registry.");
  };

  // --- Backward Compatibility ---
  window.__GRPCWEB_DEVTOOLS__.registerProto = function (protoDefinition) {
    console.warn('[gRPC Debugger] registerProto 已停用，請改用 registerService / registerMessages');
  };

  window.__GRPCWEB_DEVTOOLS__.registerMethod = function (
    methodPath,
    requestType,
    responseType,
  ) {
    bridge.enqueueSchema(
      {
        services: [
          {
            name: methodPath.split('/').slice(-2, -1)[0] || methodPath,
            fullName: methodPath.split('/').slice(1, -1).join('.') || methodPath,
            methods: [
              {
                name: methodPath.split('/').pop() || methodPath,
                requestType,
                responseType,
              },
            ],
          },
        ],
      },
      'frontend-api:method'
    );
  };
  // -----------------------------

  // ============================================================================
  // Auto-Detection: google-protobuf (window.proto) and protobufjs (window.protobuf)
  // ============================================================================

  /**
   * 從 google-protobuf 的 proto namespace 提取 schema
   * 結構：proto.package.name.MessageName
   */
  function extractFromGoogleProtobuf(protoObj, path = "") {
    const messages = {};
    const services = [];

    for (const key of Object.keys(protoObj)) {
      const value = protoObj[key];
      if (!value) continue;

      const fullName = path ? `${path}.${key}` : key;

      if (typeof value === "function") {
        // 檢查是否為 Message（有 serializeBinary 方法）
        if (
          typeof value.serializeBinary === "function" ||
          typeof value.prototype?.serializeBinary === "function"
        ) {
          const fields = [];
          try {
            // 試著從實例取得欄位資訊
            const instance = new value();
            if (instance.toObject) {
              const obj = instance.toObject();
              let fieldNum = 1;
              for (const fieldName of Object.keys(obj)) {
                let guessedType = 9; // 預設 string
                const val = obj[fieldName];

                if (Array.isArray(val)) {
                  // 如果陣列裡面有物件或者是空陣列，暫且當作 message (11)
                  // 如果陣列裡面是 primitives，則是 repeated scalar
                  if (val.length > 0 && typeof val[0] !== "object") {
                    if (typeof val[0] === "number") guessedType = 13;
                    else if (typeof val[0] === "boolean") guessedType = 8;
                    else guessedType = 9;
                  } else {
                    guessedType = 11;
                  }
                } else if (typeof val === "object" && val !== null) {
                  guessedType = 11;
                } else if (typeof val === "boolean") {
                  guessedType = 8;
                } else if (typeof val === "number") {
                  guessedType = 13;
                }

                fields.push({
                  number: fieldNum++,
                  name: fieldName,
                  type: guessedType,
                  type_name: "",
                });
              }
            }
          } catch {}

          messages[fullName] = {
            name: key,
            fullName,
            fields,
            _source: "google-protobuf",
          };
        }
        // 檢查是否為 Service Client (通常會有某個 Client 尾碼或特定的原型方法)
        else if (key.endsWith("Client") || value.name?.endsWith("Client")) {
          const serviceMethods = [];
          for (const methodKey of Object.keys(value.prototype || {})) {
            // gRPC-Web 生成的方法通常沒有大寫開頭，且不是內建方法
            if (
              typeof value.prototype[methodKey] === "function" &&
              !["constructor", "serializeBinary", "toObject"].includes(
                methodKey,
              )
            ) {
              serviceMethods.push({
                name: methodKey,
                requestType: "", // 無法直接從 function 取得類型名稱
                responseType: "",
              });
            }
          }
          if (serviceMethods.length > 0) {
            services.push({
              name: key.replace("Client", ""),
              fullName,
              methods: serviceMethods,
            });
          }
        }
      }

      // 檢查是否為嵌套 namespace
      if (
        typeof value === "object" &&
        !Array.isArray(value) &&
        value !== null
      ) {
        const nested = extractFromGoogleProtobuf(value, fullName);
        Object.assign(messages, nested.messages);
        services.push(...nested.services);
      }
    }

    return { messages, services };
  }

  /**
   * 自動偵測並註冊本地 proto library
   */
  function autoDetectLocalProtos() {
    let found = false;

    // 1. 檢查 google-protobuf 的 window.proto
    if (window.proto && typeof window.proto === "object") {
      console.log("[gRPC Debugger] Detected google-protobuf (window.proto)");
      try {
        const result = extractFromGoogleProtobuf(window.proto);
        const messageCount = Object.keys(result.messages).length;

        if (messageCount > 0) {
          bridge.enqueueSchema(result, 'auto-detect:google-protobuf');
          console.log(
            `[gRPC Debugger] Auto-registered ${messageCount} messages from window.proto`,
          );
          found = true;
        }
      } catch (e) {
        console.warn("[gRPC Debugger] Failed to extract from window.proto:", e);
      }
    }

    // 2. 檢查 protobufjs 的 window.protobuf
    if (window.protobuf?.Root) {
      console.log("[gRPC Debugger] Detected protobuf.js (window.protobuf)");
      // protobufjs 需要不同的處理方式，這裡先標記偵測到
      // 實際提取需要遍歷 Root
      found = true;
    }

    // 通知 extension 是否找到本地 proto
    return found;
  }

  // ============================================================================
  // Interceptor 已解碼模式 API
  // 供前端 gRPC interceptor 直接傳送已序列化為 JSON 的 call data
  // ============================================================================

  /**
   * 公開 API：前端 interceptor 可呼叫此方法直接送入已解碼的 gRPC call
   * @param {Object} data - 已解碼的 call data
   * @param {string} data.method - 完整的 service/method 路徑 (例如 "pkg.Service/Method")
   * @param {string} [data.methodType='unary'] - 呼叫類型
   * @param {Object} data.request - 已解碼的 JSON request
   * @param {Object} data.response - 已解碼的 JSON response
   * @param {Object|null} [data.error] - 錯誤資訊 (若有)
   */
  window.__GRPCWEB_DEVTOOLS__.sendCall = function (data) {
    if (!data || !data.method) {
      console.warn("[gRPC Debugger] sendCall: 缺少 method 參數");
      return;
    }

    bridge.enqueueCall(createCallEvent(data));
  };

  // ============================================================================
  // Legacy postMessage 相容層
  //
  // 保留舊格式訊息的接入能力，但統一轉成 bridge hint / schema event。
  // ============================================================================

  window.addEventListener("message", (event) => {
    const msg = event.data;

    if (msg?.source === bridgeEventSource && msg?.action === 'enqueueBridgeEvent' && msg.payload) {
      bridge.enqueueEvent(msg.payload);
      return;
    }

    if (event.source !== window) return;

    if (msg?.type === postType && msg?.action === 'registerSchema' && msg.schema) {
      bridge.enqueueSchema(msg.schema, msg.source || 'legacy-postmessage');
      return;
    }

    if (msg?.type === postType && msg?.action === 'gRPCNetworkCall') {
      bridge.enqueueCall(createCallEvent(msg));
      return;
    }

    if (
      msg?.source === "grpc-web-devtools" &&
      msg?.action?.type === "unary-request"
    ) {
      const payload = msg.action.payload?.partial;
      if (!payload) return;

      bridge.enqueueCall(createCallEvent({
        method: normalizeMethodPath(payload.url) || payload.url || '',
        methodType: payload.type || 'unary',
        request: payload.request || null,
        response: payload.response?.body || payload.response || null,
        error:
          payload.status && payload.status !== 0
            ? { code: payload.status, message: String(payload.response) }
            : null,
        timestamp: payload.id || Date.now(),
      }));
      return;
    }
  });

  // 延遲執行自動偵測，等待頁面載入完成
  if (document.readyState === "complete") {
    setTimeout(autoDetectLocalProtos, 500);
  } else {
    window.addEventListener("load", () =>
      setTimeout(autoDetectLocalProtos, 500),
    );
  }

  window.dispatchEvent(new CustomEvent("grpc-web-dev-tools-ready"));
})();
